version: '1.0'
name: Build Windows

triggers:
  manual:
    ref:
      - tauri

stages:
  - stage:
      name: build-win
      jobs:
        - job:
            name: dist-win
            runs-on: Windows
            steps:
              - step: git-checkout

              - step:
                  name: Setup Rust
                  run: |
                    rustup target add x86_64-pc-windows-msvc

              - step:
                  name: Install dependencies
                  run: npm ci

              - step:
                  name: Build Tauri (Windows x64)
                  run: npm run dist:win

              - step:
                  name: List output
                  run: dir src-tauri\target\x86_64-pc-windows-msvc\release\bundle
